#!/bin/bash

set -e

source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh

# compatibility symlinks so we hide SCL paths
if [ -v HTTPD_SCL ] ; then
  # /opt/rh/httpd24/root/etc/httpd will be symlink to /etc/httpd
  mv /opt/rh/httpd24/root/etc/httpd /etc/httpd
  ln -s /etc/httpd /opt/rh/httpd24/root/etc/httpd

  # /opt/rh/httpd24/root/var/run/httpd will be symlink to /var/run/httpd
  mv /opt/rh/httpd24/root/var/run/httpd /var/run/httpd
  ln -s /var/run/httpd /opt/rh/httpd24/root/var/run/httpd

  # /opt/rh/httpd24/root/var/www will be symlink to /var/www
  rm -rf /var/www
  mv /opt/rh/httpd24/root/var/www /var/www
  ln -s /var/www /opt/rh/httpd24/root/var/www
fi

if head "/etc/redhat-release" | grep -q "^Red Hat Enterprise Linux release 8"; then
    /usr/libexec/httpd-ssl-gencerts
fi

mkdir -p ${HTTPD_CONFIGURATION_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_D_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_MODULES_D_PATH}

# Generate self-signed cert
openssl genrsa -out /etc/pki/tls/private/ca.key 2048
openssl req -new -x509 -days 365 -key /etc/pki/tls/private/ca.key -subj "/C=CN/ST=GD/L=SZ/O=Acme, Inc./CN=Acme Root CA" -out /etc/pki/tls/certs/ca.crt

openssl req -newkey rsa:2048 -nodes -keyout /etc/pki/tls/private/localhost.key -subj "/C=CN/ST=GD/L=SZ/O=Acme, Inc./CN=localhost" -out /etc/pki/tls/certs/server.csr
openssl x509 -req -extfile <(printf "subjectAltName=DNS:localhost,DNS:localhost") -days 365 -in /etc/pki/tls/certs/server.csr -CA /etc/pki/tls/certs/ca.crt -CAkey /etc/pki/tls/private/ca.key -CAcreateserial -out /etc/pki/tls/certs/localhost.crt

chmod -R a+r   /etc/pki/tls/certs/localhost.crt
chmod -R a+r   /etc/pki/tls/private/localhost.key
mkdir -p ${HTTPD_APP_ROOT}/etc
chmod -R a+rwx ${HTTPD_APP_ROOT}/etc
chmod -R a+rwx ${HTTPD_VAR_RUN}
chown -R 1001:0 ${HTTPD_APP_ROOT}
chown -R 1001:0 ${HTTPD_DATA_PATH}
chown -R 1001:0 ${HTTPD_LOG_PATH}

mkdir -p ${HTTPD_CONTAINER_SCRIPTS_PATH}/pre-init

config_general

