#!/bin/bash

set -e

source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh

# compatibility symlinks so we hide SCL paths
if [ -v HTTPD_SCL ] ; then
  # /opt/rh/httpd24/root/etc/httpd will be symlink to /etc/httpd
  mv /opt/rh/httpd24/root/etc/httpd /etc/httpd
  ln -s /etc/httpd /opt/rh/httpd24/root/etc/httpd

  # /opt/rh/httpd24/root/var/run/httpd will be symlink to /var/run/httpd
  mv /opt/rh/httpd24/root/var/run/httpd /var/run/httpd
  ln -s /var/run/httpd /opt/rh/httpd24/root/var/run/httpd

  # /opt/rh/httpd24/root/var/www will be symlink to /var/www
  rm -rf /var/www
  mv /opt/rh/httpd24/root/var/www /var/www
  ln -s /var/www /opt/rh/httpd24/root/var/www
fi

if head "/etc/redhat-release" | grep -q "^Red Hat Enterprise Linux release 8"; then
    /usr/libexec/httpd-ssl-gencerts
fi

if [ -z ${TLS_KEY_PATH+x} ]
then
  TLS_KEY_PATH=/etc/pki/httpd/tls.key
fi

if [ -z ${TLS_CERT_PATH+x} ]
then
  TLS_CERT_PATH=/etc/pki/httpd/tls.crt
fi

sed -i "s#SSLCertificateFile.*#SSLCertificateFile ${TLS_CERT_PATH}#g" /etc/httpd/conf.d/ssl.conf
sed -i "s#SSLCertificateKeyFile.*#SSLCertificateKeyFile ${TLS_KEY_PATH}#g" /etc/httpd/conf.d/ssl.conf

mkdir -p ${HTTPD_CONFIGURATION_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_D_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_MODULES_D_PATH}

mkdir -p ${HTTPD_APP_ROOT}/etc
chmod -R a+rwx ${HTTPD_APP_ROOT}/etc
chmod -R a+rwx ${HTTPD_VAR_RUN}
chown -R 1001:0 ${HTTPD_APP_ROOT}
chown -R 1001:0 ${HTTPD_DATA_PATH}
chown -R 1001:0 ${HTTPD_LOG_PATH}

mkdir -p ${HTTPD_CONTAINER_SCRIPTS_PATH}/pre-init

config_general

